name: Build EXE

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Baixar Bat To Exe Converter
      run: |
        Invoke-WebRequest -Uri "https://github.com/tokyoneon/B2E/raw/master/Bat_To_Exe_Converter.exe" -OutFile "B2E.exe"

    - name: Procurar arquivo BAT e Compilar para EXE
      shell: powershell
      run: |
        $batFile = Get-ChildItem -Filter "*.bat" | Select-Object -First 1
        if (-not $batFile) {
            Write-Error "Nenhum arquivo .bat foi encontrado no repositorio!"
            exit 1
        }
        Write-Host "Arquivo encontrado: $($batFile.Name)"
        .\B2E.exe /bat "$($batFile.FullName)" /exe "dist/ConfiguradorRede.exe" /admin 1 /invisible 0

    - name: Upload do EXE pronto
      uses: actions/upload-artifact@v4
      with:
        name: ConfiguradorRede
        path: dist/ConfiguradorRede.exe
